name: Generate Diagrams


on:
  pull_request:
    branches: [ main ]
  workflow_dispatch:


jobs:
  generate-diagrams:
    runs-on: ubuntu-latest
    steps:
    
      - name: Checkout
        uses: actions/checkout@v3
        
      - name: Generate Diagrams
        uses: grassedge/generate-plantuml-action@v1.5
        with:
          path: docs/diagrams
          message: "chore: generate diagrams"
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
          
      - name: Comment PR
        uses: thollander/actions-comment-pull-request@v1
        with:
          message: |
            Your diagram is ready to serve
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}


      
      
