name: Generate Diagrams


on:
  pull_request:
    branches: [ main ]
  workflow_dispatch:


jobs:
  generate-diagrams:
    env:
      UML_FILES: ".puml"
    runs-on: ubuntu-latest
    steps:
    
      - name: Checkout
        uses: actions/checkout@v3
        
      - name: Get changed UML files
        id: getfile
        run: |
          echo "::set-output name=files::$(git diff --name-only origin/main origin/${GITHUB_HEAD_REF} | grep .puml | xargs)"
          
      - name: Generate SVG Diagrams
        uses: cloudbees/plantuml-github-action@master
        with:
            args: -v -tsvg ${{ steps.getfile.outputs.files }}

      - name: Push Local Changes
        uses:  stefanzweifel/git-auto-commit-action@v4.14.1
        with: 
          commit_user_name: "diagram-generator"
          commit_user_email: "pjaswo1204@gmail.com"
          commit_author: "Diagram Generator <pjaswo1204@gmail.com>"
          commit_message: "chore: re-generate UML diagrams" 
          branch: ${{ github.head_ref }}
          
      - name: Comment PR
        uses: thollander/actions-comment-pull-request@v1
        with:
          message: |
            Your diagram is ready to serve
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}


      
      