name: Generate Diagrams


on:
  pull_request:
    branches: [ main ]
  workflow_dispatch:


jobs:
  generate-diagrams:
    env:
      UML_FILES: ".puml"
    runs-on: ubuntu-latest
    steps:
    
      - name: Checkout
        uses: actions/checkout@v3

      - name: Get UML files
        id: getfile
        uses: technote-space/get-diff-action@v6
        with:
          PATTERNS: '*.puml'
          
      - name: Generate SVG Diagrams
        uses: cloudbees/plantuml-github-action@master
        with:
            args: -v -tsvg ${{ steps.getfile.outputs.diff }}

      - name: Generate Diagrams' directory
        id: getdiagramdir
        run: |
          DIAGRAM_CODE=${{ steps.getfile.outputs.diff }}
          DIAGRAM_IMG="${DIAGRAM_CODE//.puml/.svg}"
          echo "::set-output name=diagramdir::$DIAGRAM_IMG"

      - name: Push Local Changes
        uses: stefanzweifel/git-auto-commit-action@v4.14.1
        with: 
          commit_user_name: "diagram-generator"
          commit_user_email: "pjaswo1204@gmail.com"
          commit_author: "Diagram Generator <pjaswo1204@gmail.com>"
          commit_message: "chore: re-generate UML diagrams" 
          branch: ${{ github.head_ref }}

      - name: Comment PR
        uses: thollander/actions-comment-pull-request@v1
        with:
          message: |
            Your new diagram is ready
            ![new-diagram](https://raw.githubusercontent.com/paskahlisanjas/diagram-as-code/${{ github.event.pull_request.head.sha }}/${{ steps.getdiagramdir.outputs.diagramdir }})
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}


      
      